const hotelData = [
    {
        id: 1,
        name: 'Light bright airy stylish apt & safe peaceful stay',
        badeRooms: '4 guests 2 bedrooms 2 beds 2 baths',
        condition: 'Wifi Air conditioning Kitchen',
        others: 'Cancellation fexibility availiable',
        rating: '4.9(33)',
        price: '$34/night',
        photo: 'https://cf.bstatic.com/images/hotel/max1024x768/208/208038194.jpg',
    },
    {
        id: 1,
        name: 'Apartment in Lost Panorama',
        badeRooms: '4 guests 2 bedrooms 2 beds 2 baths',
        condition: 'Wifi Air conditioning Kitchen',
        others: 'Cancellation fexibility availiable',
        rating: '4.8(20)',
        price: '$52/night',
        photo: 'https://sitecore-cd-imgr.shangri-la.com/MediaFiles/0/E/8/%7B0E804162-321D-42D5-992C-CEC0F9A2C1F4%7D200709_slcom_shangrilastaycation.jpg?width=750&quality=90',
    },
    {
        id: 1,
        name: 'AR Lounge & Pool (r&r + b&b)',
        badeRooms: '4 guests 2 bedrooms 2 beds 2 baths',
        condition: 'Wifi Air conditioning Kitchen',
        others: 'Cancellation fexibility availiable',
        rating: '4.9(10)',
        price: '$44/night',
        photo: 'https://pix10.agoda.net/hotelImages/4843159/-1/44609f66708f1fef74f1be27374c9740.jpg?s=1024x768',
    },
    {
        id: 3,
        name: 'Sundarban Royal Eco Resort',
        badeRooms: '4 guests 2 bedrooms 2 beds 2 baths',
        condition: 'Wifi Air conditioning Kitchen',
        others: 'Cancellation fexibility availiable',
        rating: '4.9(33)',
        price: '$34/night',
        photo: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEyMDd9',
    },
    {
        id: 3,
        name: 'Prakrity Village Resort Sundarbans',
        badeRooms: '4 guests 2 bedrooms 2 beds 2 baths',
        condition: 'Wifi Air conditioning Kitchen',
        others: 'Cancellation fexibility availiable',
        rating: '4.8(20)',
        price: '$52/night',
        photo: 'https://res.cloudinary.com/simplotel/image/upload/x_0,y_215,w_4288,h_2412,c_crop,q_80,fl_progressive/w_600,h_337,f_auto,c_fit/pride-hotel-bengaluru/Hotel_Exterior_Bldg_qzx0kh',
    },
    {
        id: 3,
        name: 'Royal Sundarban Wild Resort',
        badeRooms: '4 guests 2 bedrooms 2 beds 2 baths',
        condition: 'Wifi Air conditioning Kitchen',
        others: 'Cancellation fexibility availiable',
        rating: '4.9(10)',
        price: '$44/night',
        photo: 'https://cf.bstatic.com/images/hotel/max1024x768/210/210875998.jpg',
    },
    {
        id: 2,
        name: 'HOTEL- GREEN LEAF GUEST HOUSE',
        badeRooms: '4 guests 2 bedrooms 2 beds 2 baths',
        condition: 'Wifi Air conditioning Kitchen',
        others: 'Cancellation fexibility availiable',
        rating: '4.9(33)',
        price: '$34/night',
        photo: 'https://images.unsplash.com/photo-1576675784201-0e142b423952?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80',
    },
    {
        id: 2,
        name: 'Grand Selim Resort & Tour',
        badeRooms: '4 guests 2 bedrooms 2 beds 2 baths',
        condition: 'Wifi Air conditioning Kitchen',
        others: 'Cancellation fexibility availiable',
        rating: '4.8(20)',
        price: '$52/night',
        photo: 'https://res.cloudinary.com/simplotel/image/upload/w_5000,h_3883/x_10,y_0,w_4990,h_2804,c_crop,q_90,fl_progressive/w_600,h_337,f_auto,c_fit/the-orchid-hotel-mumbai-vile-parle/Lobby_2,_Orchid_Hotel_Mumbai_Vile_Parle,_5_Star_Hotel_in_Vile_Parle',
    },
    {
        id: 2,
        name: 'Sreemangal Inn Hotel and Restaurant',
        badeRooms: '4 guests 2 bedrooms 2 beds 2 baths',
        condition: 'Wifi Air conditioning Kitchen',
        others: 'Cancellation fexibility availiable',
        rating: '4.9(10)',
        price: '$44/night',
        photo: 'https://i2.wp.com/thepointsguy.com/wp-content/uploads/2020/02/AC-Hotel-Park-City.jpg?fit=1440%2C960px&ssl=1',
    },
]
export default hotelData;